import PolicyShell, { PolicySection, PolicyHighlight } from "@/components/PolicyShell";

const PrivacyPolicyPage = () => (
  <PolicyShell
    icon="🔒"
    title="Privacy Policy"
    subtitle="How we collect, use, and protect your personal information."
    lastUpdated="23 May 2025"
  >
    <PolicyHighlight variant="default">
      This Privacy Policy applies to the website operated by <strong>BHUPATI DARMARAO</strong>{" "}
      and governs all data practices in connection with the ₹1 Quest platform. By using this
      platform, you agree to the terms described herein.
    </PolicyHighlight>

    <PolicySection number={1} title="Information We Collect">
      <p>We collect the following categories of personal information when you use our platform:</p>
      <ul className="list-disc pl-5 space-y-1 mt-1">
        <li>
          <strong className="text-foreground">Account Information:</strong> Email address and
          password (hashed) used to create and authenticate your account.
        </li>
        <li>
          <strong className="text-foreground">Profile Data:</strong> Display name, username, and
          any optional profile information you voluntarily provide.
        </li>
        <li>
          <strong className="text-foreground">Payment Data:</strong> Transaction ID, payment
          status, and order metadata generated by Razorpay. We do <em>not</em> store your card
          number, UPI ID, or any sensitive financial instrument details — these are handled
          exclusively by Razorpay's PCI-DSS compliant infrastructure.
        </li>
        <li>
          <strong className="text-foreground">Usage Data:</strong> Pages visited, referral codes
          used, feature interactions, and timestamps, collected automatically via server logs.
        </li>
        <li>
          <strong className="text-foreground">Device &amp; Network Data:</strong> IP address,
          browser type, and operating system — collected for security and fraud prevention purposes.
        </li>
      </ul>
    </PolicySection>

    <PolicySection number={2} title="How We Use Your Information">
      <p>Your information is used solely for the following purposes:</p>
      <ul className="list-disc pl-5 space-y-1 mt-1">
        <li>To create and maintain your account on the platform.</li>
        <li>To process your ₹1 payment via Razorpay and activate your access.</li>
        <li>To display your name/username on the public leaderboard and wall of legends.</li>
        <li>To track XP, ranks, referrals, and other gamification features.</li>
        <li>To respond to support queries sent to our email address.</li>
        <li>To detect, investigate, and prevent fraudulent activity.</li>
        <li>To comply with applicable Indian laws and regulatory requirements.</li>
      </ul>
    </PolicySection>

    <PolicySection number={3} title="Data Sharing &amp; Disclosure">
      <p>
        We do not sell, rent, or trade your personal data to any third party. Data is shared
        only in the following limited circumstances:
      </p>
      <ul className="list-disc pl-5 space-y-1 mt-1">
        <li>
          <strong className="text-foreground">Razorpay:</strong> As our payment gateway provider,
          Razorpay processes your payment data under their own Privacy Policy and security
          standards.
        </li>
        <li>
          <strong className="text-foreground">Supabase:</strong> Our database and authentication
          infrastructure provider. Data is stored on secure, encrypted servers.
        </li>
        <li>
          <strong className="text-foreground">Legal Obligation:</strong> We may disclose
          information when required by Indian law, a court order, or a governmental authority.
        </li>
      </ul>
    </PolicySection>

    <PolicySection number={4} title="Data Retention">
      <p>
        We retain your account data for as long as your account remains active. If you request
        account deletion, your personal data will be removed within <strong>30 days</strong>,
        except where retention is required by law (e.g., financial transaction records, which
        are retained for 7 years as per Indian financial regulations).
      </p>
    </PolicySection>

    <PolicySection number={5} title="Cookies &amp; Tracking">
      <p>
        We use essential cookies and local browser storage to maintain your login session and
        preferences. We do not use tracking cookies for advertising. No third-party analytics
        platforms (e.g., Google Analytics) are currently deployed on this platform.
      </p>
    </PolicySection>

    <PolicySection number={6} title="Your Rights">
      <p>As a user, you have the right to:</p>
      <ul className="list-disc pl-5 space-y-1 mt-1">
        <li>Request access to the personal data we hold about you.</li>
        <li>Request correction of inaccurate or incomplete data.</li>
        <li>Request deletion of your account and associated personal data.</li>
        <li>Withdraw consent for any optional data processing.</li>
      </ul>
      <p className="mt-2">
        To exercise any of these rights, email us at{" "}
        <a
          href="mailto:bhupathi.dharmarao@outlook.com"
          className="text-accent hover:underline"
        >
          bhupathi.dharmarao@outlook.com
        </a>
        . We will respond within 24–48 business hours.
      </p>
    </PolicySection>

    <PolicySection number={7} title="Security">
      <p>
        We implement industry-standard security measures including HTTPS (TLS) encryption,
        password hashing, and Row Level Security (RLS) at the database layer. Payment transactions
        are handled entirely by Razorpay and are never stored on our servers in raw form.
        Despite these measures, no system is 100% secure; you use the platform at your own risk.
      </p>
    </PolicySection>

    <PolicySection number={8} title="Contact for Privacy Queries">
      <p>
        For any privacy-related queries or concerns, please contact us at:
      </p>
      <div className="mt-2 duo-card text-sm space-y-1 !py-4">
        <p><strong className="text-foreground">Name:</strong> BHUPATI DARMARAO</p>
        <p>
          <strong className="text-foreground">Email:</strong>{" "}
          <a href="mailto:bhupathi.dharmarao@outlook.com" className="text-accent hover:underline">
            bhupathi.dharmarao@outlook.com
          </a>
        </p>
        <p><strong className="text-foreground">Address:</strong> Shanti Nagar, Ramanthapur, Hyderabad, Telangana — 500013</p>
      </div>
    </PolicySection>
  </PolicyShell>
);

export default PrivacyPolicyPage;
